// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccbkksxrfmmatptawpmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjYmtrc3hyZm1tYXRwdGF3cG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MDcxOTgsImV4cCI6MjA4OTQ4MzE5OH0.ZlznMO7dds0ogi70V2UyueOSQvAFXqweXL6QyhP4P2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});